### ISSUE TITLE
Anime-Planet and AniDB ratings aren't loading up

### ISSUE THREAD

**Issue by K0-RR** [infanf/myanili#73]
There are errors present related to anidb in the browser console: 
`Access to fetch at 'https://mal.myani.li/anidb/httpapi?client=myanilist&clientver=2&protover=1&request=anime&aid=15421&with-credits=1' from origin 'https://myani.li' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

As for anime-planet, no idea but since they are the only ones without API...

Other error:
```
ERROR Error: Uncaught (in promise): TypeError: Failed to fetch
TypeError: Failed to fetch
    at polyfills.5cd009b2d66d005e.js:1:21597
    at i.<computed> (polyfills.5cd009b2d66d005e.js:1:15203)
    at 124.cf0feebf5b8ce355.js:1:12286
    at Generator.next (<anonymous>)
    at i (main.cef4243b2b3f2b7c.js:461:605821)
    at ie (main.cef4243b2b3f2b7c.js:461:606027)
    at main.cef4243b2b3f2b7c.js:461:606090
    at new u (polyfills.5cd009b2d66d005e.js:1:18824)
    at main.cef4243b2b3f2b7c.js:461:605966
    at o.getXml (124.cf0feebf5b8ce355.js:1:12366)
    at W (polyfills.5cd009b2d66d005e.js:1:17778)
    at W (polyfills.5cd009b2d66d005e.js:1:17327)
    at polyfills.5cd009b2d66d005e.js:1:18610
    at f.invokeTask (polyfills.5cd009b2d66d005e.js:1:8352)
    at Object.onInvokeTask (main.cef4243b2b3f2b7c.js:461:309946)
    at f.invokeTask (polyfills.5cd009b2d66d005e.js:1:8273)
    at f.runTask (polyfills.5cd009b2d66d005e.js:1:3384)
    at ee (polyfills.5cd009b2d66d005e.js:1:10749)
```

**Comment by RDKRACZ** [comment]
Sometimes the AniDB and Anime-Planet rows aren't even appearing: https://myani.li/#/anime/details/55818.

**Comment by nattadasu** [comment]
> Sometimes the AniDB and Anime-Planet rows aren't even appearing

For this, it is because [MyAniLi loads the IDs from LiveChart API](https://github.com/infanf/myanili/blob/main/frontend/src/app/services/anime/livechart.service.ts) (see https://www.livechart.me/anime/12225), but then again AniDB won't have separate entry as it is considered ["Special Episode"](https://anidb.net/episode/268721) on [S2 entry](https://anidb.net/anime/17236), so don't expect prequel, ova, or special to be separate entry on AniDB. For the rest of future entry, I do think it's better for the app to allow manual edit whenever those ID can't be found.

*for fetching anime-planet score, the only way is scraping its html content lol*

**Comment by infanf** [comment]
@RDKRACZ thanks for reporting this. I am aware that the aniDB ratings aren't loading. Problem is, that my server has been banned from accessing aniDB because it made too many requests. Sadly there is no way to regain access. I will disable the request until I find another way to access the aniDB API.
Regarding the anime-planet ratings: it is planned to scrape them (see indescriptive issue #60) but I haven't come around to implementing a scraper yet.

**Comment by nattadasu** [comment]
Regarding aniDB score, I used a public dump file by Shoko Anime for one of my project.

I don't know how frequent the entries were getting updated (due to anidb's archaic anti-ddos measurement), but assuming they update weekly, seems wouldn't be a problem to showcase a score.

Additionally, the data itself is a 1:1 offline data you can get in Anime info page of an entry compared what anidb officially published on their wiki. 

Anipla on another hand tho 🗿

**Comment by infanf** [comment]
It's been a while 😅 I've since moved the deployment to Google cloud, which should've fixed the rate limit issue. But now all requests lead to a 500 server error. Issue here is the caching:

```ERROR: Unable to open database: unable to open database file {"exception":"[object] (Exception(code: 0): Unable to open database: unable to open database file at /app/app/Http/Controllers/AnidbController.php:69)"} []```

I'll check it out the upcoming days
